version: "3.4"
x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  prometheus:
    image: prom/prometheus
    ports:
     - 9090:9090
    volumes:
     - /etc/prometheus:/etc/prometheus
     - prometheus_data:/prometheus
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention=30d
#      --web.enable-admin-api
    restart: unless-stopped
    logging: *default-logging

    
volumes:
    prometheus_data: